config/routes.rb
Rails.application.routes.draw do
  resources :job_boards
  resources :mentorship
  resources :development
  resources :teams, only: [ :index, :show, :edit, :update ] do
    resources :team_members, only: [ :edit, :update ]
  end

  root "pages#home"

  get "teams", to: "teams#index"
  get "job_boards", to: "job_boards#show"
  get "mentorship", to: "pages#mentorship"
  get "development", to: "pages#development"
  get "/.well-known/funding-manifest-urls", to: "well_known#funding_manifest_urls"



  # Route for the contact form submission
  # get '/contact', to: 'pages#new_contact', as: 'new_contact'
  post "/contact", to: "pages#submit_contact"

  # Health status for uptime monitors
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA service worker and manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/job_board.rb
class JobBoard < ApplicationRecord
end

app/controllers/job_boards_controller.rb
class JobBoardsController < ApplicationController
  before_action :set_job_board, only: %i[ show edit update destroy ]

  # GET /job_boards or /job_boards.json
  def index
    @job_boards = JobBoard.all
  end

  # GET /job_boards/1 or /job_boards/1.json
  def show
  end

  # GET /job_boards/new
  def new
    @job_board = JobBoard.new
  end

  # GET /job_boards/1/edit
  def edit
  end

  # POST /job_boards or /job_boards.json
  def create
    @job_board = JobBoard.new(job_board_params)

    respond_to do |format|
      if @job_board.save
        format.html { redirect_to @job_board, notice: "Job board was successfully created." }
        format.json { render :show, status: :created, location: @job_board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_boards/1 or /job_boards/1.json
  def update
    respond_to do |format|
      if @job_board.update(job_board_params)
        format.html { redirect_to @job_board, notice: "Job board was successfully updated." }
        format.json { render :show, status: :ok, location: @job_board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_boards/1 or /job_boards/1.json
  def destroy
    @job_board.destroy!

    respond_to do |format|
      format.html { redirect_to job_boards_path, status: :see_other, notice: "Job board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_board
      @job_board = JobBoard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_board_params
      params.require(:job_board).permit(:index)
    end
end

app/helpers/job_boards_helper.rb
module JobBoardsHelper
end

app/views/job_boards/_form.html.erb
<%= form_with(model: job_board) do |form| %>
  <% if job_board.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_board.errors.count, "error") %> prohibited this job_board from being saved:</h2>

      <ul>
        <% job_board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_boards/_job_board.html.erb
<div id="<%= dom_id job_board %>">
  <p>
    <strong>Index:</strong>
    <%= job_board.index %>
  </p>

</div>

app/views/job_boards/edit.html.erb
<% content_for :title, "Editing job board" %>

<h1>Editing job board</h1>

<%= render "form", job_board: @job_board %>

<br>

<div>
  <%= link_to "Show this job board", @job_board %> |
  <%= link_to "Back to job boards", job_boards_path %>
</div>

app/views/job_boards/index.html.erb
<!-- job_boards/index.html.erb -->

<div class="job-boards-page">
  <p style="color: green"><%= notice %></p>

  <% content_for :title, "Job boards" %>
  <!-- Job Board -->
  <br> 
  <section id="about" class="py-5">
    <div class="container">
        <h2 class="text-center mb-4 text-black">The Mama Tech Job Board</h2>
        <p class="p-text">
        <img src="<%= asset_path('coming_soon.jpg') %>" alt="Job Board Image" class="img-fluid full-screen-image">
        </p>
    </div>
  </section>
  <div id="job_boards">
    <% @job_boards.each do |job_board| %>
      <%= render job_board %>
      <p>
        <%= link_to "Show this job board", job_board %>
      </p>
    <% end %>
  </div>
</div>

<!-- <%= link_to "New job board", new_job_board_path %> -->

app/views/job_boards/new.html.erb
<% content_for :title, "New job board" %>

<h1>New job board</h1>

<%= render "form", job_board: @job_board %>

<br>

<div>
  <%= link_to "Back to job boards", job_boards_path %>
</div>

app/views/job_boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_board %>

<div>
  <%= link_to "Edit this job board", edit_job_board_path(@job_board) %> |
  <%= link_to "Back to job boards", job_boards_path %>

  <%= button_to "Destroy this job board", @job_board, method: :delete %>
</div>