config/routes.rb
Rails.application.routes.draw do
  resources :job_boards
  resources :mentorship
  resources :development
  resources :teams, only: [ :index, :show, :edit, :update ] do
    resources :team_members, only: [ :edit, :update ]
  end

  root "pages#home"

  get "teams", to: "teams#index"
  get "job_boards", to: "job_boards#show"
  get "mentorship", to: "pages#mentorship"
  get "development", to: "pages#development"
  get "/.well-known/funding-manifest-urls", to: "well_known#funding_manifest_urls"



  # Route for the contact form submission
  # get '/contact', to: 'pages#new_contact', as: 'new_contact'
  post "/contact", to: "pages#submit_contact"

  # Health status for uptime monitors
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA service worker and manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="bg-black text-white text-center py-3">
    <p>&copy; <%= Time.now.year %> Mama Tech. All rights reserved.</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top mb-0">
    <div class="container-fluid">
        <div class="">
            <a class="navbar-brand text-danger" href="#hero">
            <%= image_tag "mltlogo.png", alt: "Mama Tech Logo", class: "logo-class mx-5 img-fluid", style: "max-width: 100px;" %>
            </a>
        </div>
        <button type="button" class="navbar-toggler mx-5" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto mb-2 mb-lg-2">
            <%= link_to "About Us", root_path(anchor: "about"), class: "nav-link me-5 text-lg" %>
            <%= link_to "Services", root_path(anchor: "services"), class: "nav-link me-5 text-lg" %>
            <%= link_to "Contact", root_path(anchor: "contact"), class: "nav-link me-5 text-lg" %>
            <%= link_to "Job Board", job_boards_path, class: "nav-link me-5 text-lg" %>
            <div>
                <%= link_to "Join Us", root_path(anchor: "contact"), class: "btn btn-danger text-white me-5" %>
            </div>
            </div>
        </div>
    </div>
</nav>